"""
Application-wide constants for limits, timeouts, and configuration values.
"""

# OpenAI API Configuration
OPENAI_API_TIMEOUT_SECONDS = 30.0
OPENAI_TEMPERATURE = 0.2
OPENAI_MODEL = "gpt-4o-mini"

# Input Length Limits
MAX_BUG_REPORT_INPUT_LENGTH = 1000
MAX_TEXT_LENGTH = 1000
MIN_TEXT_LENGTH = 3
MIN_PROJECT_OVERVIEW_LENGTH = 50
MIN_BUG_REPORT_TEMPLATE_LENGTH = 25

# Jira Configuration
JIRA_CLIENT_TIMEOUT_SECONDS = 10
MAX_JIRA_TOKEN_LENGTH = 500
MIN_JIRA_TOKEN_LENGTH = 10
MAX_JIRA_URL_LENGTH = 100
MAX_JIRA_QUERY_LENGTH = 500
MIN_JIRA_QUERY_LENGTH = 5
MAX_JIRA_EMAIL_LENGTH = 100
MAX_JIRA_ISSUES_LIMIT = 50

# Jira Default Fields
MAX_JIRA_FIELD_NAME_LENGTH = 64
MAX_JIRA_FIELD_VALUE_LENGTH = 120

# HTTP Status Codes
HTTP_STATUS_BAD_REQUEST = 400
HTTP_STATUS_UNAUTHORIZED = 401
HTTP_STATUS_FORBIDDEN = 403

# MongoDB Configuration
MONGODB_SERVER_SELECTION_TIMEOUT_MS = 5000

# Identifier Length Limits
MAX_SLACK_ID_LENGTH = 256
MAX_PROJECT_NAME_LENGTH = 128

# Server Configuration
DEFAULT_PORT = 3000
